### ISSUE TITLE
Discussion still visible in All Discussions

### ISSUE THREAD

**Issue by theAkito** [datlechin/flarum-tag-passwords#6]
If the user wants to access the particular tag, the password works.
However, the same "protected" discussion still is visible in "All Discussions" for literally everyone, even people who are not part of any group or just visitors, who aren't even registered at the forum...

**Comment by Yippy** [comment]
Hiding specific tag from all discussion, can be enabled via the tag option. That way people can't see these protected post, but people that has the URL of the discussion will still continue to see them.
![image](https://github.com/datlechin/flarum-tag-passwords/assets/6518915/411610ad-5b60-4923-a464-0687cee5c870)

**Comment by datlechin** [comment]
https://github.com/datlechin/flarum-tag-passwords/releases/tag/v0.3.0
